---
apiVersion: v1
kind: Service
metadata:
  namespace: devel
  name: nginx-hostname-deployment-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-hostname
  type: NodePort
