apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iroha-app
  namespace: irohaboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: irohaboard-container
        image: tksarah/irohaboard-app:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_HOST
          value: "iroha-db"
