apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iroha-db
  namespace: irohaboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: maria-con
        image: tksarah//iroha_db:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"

